export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const USER_ID = "USER_ID";
export const USER_EMAIL = "USER_EMAIL";
export const KIOSK_ID ="KIOSK_ID";
export const USER_FIRST_NAME = "USER_FRIST_NAME";
export const CURRENT_LOCATION_LONGITUDE= 'CURRENT_LOCATION_LONGITUDE';
export const CURRENT_LOCATION_LATITUDE= 'CURRENT_LOCATION_LATITUDE';
export const GOONG_ACCESS_MAP_KEY="GlVNPt2Vav2Z75sQm6lJ7XymStHLVD8UcWwhbWMn";
export const GOONG_ACCESS_API_KEY="NQwoYefhyHYuoUPIcU2sVKtoD5HjpbpD4oJqLi0H";

